/*
 * Copyright (c) 2026 MaybeAshleyIdk
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading;

namespace UltrakillArchipelago.SourceCodeGenerator
{
	[Generator(LanguageNames.CSharp)]
	public sealed class SlotDataClassSourceFileGenerator : IIncrementalGenerator
	{
		private const string NamespaceName = "ArchipelagoULTRAKILL";

		// System.CodeDom.Compiler.GeneratedCodeAttribute ?
		// language=c#
		private const string FileContentsTemplate = @"// <auto-generated />

#nullable enable

namespace {{NAMESPACE_NAME}}
{
	internal readonly struct SlotData
	{
		#region fields

		{{FIELDS}}

		#endregion

		private SlotData(
			{{CONSTRUCTOR_PARAMETERS}}
		)
		{
			{{CONSTRUCTOR_FIELD_ASSIGNMENTS}}
		}

		public override string ToString()
		{
			var str = ""SlotData("";

			{{TO_STRING_FIELDS}}

			str += "")"";

			return str;
		}

		public static SlotData FromLoginResult(
			global::Archipelago.MultiClient.Net.LoginSuccessful result,
			global::BepInEx.Logging.ManualLogSource logger
		)
		{
			global::System.Collections.Generic.Dictionary<string, object?> slotData = result.SlotData;

			{{FACTORY_FUNCTION_VARIABLES}}

			return new SlotData(
				{{FACTORY_FUNCTION_CONSTRUCTOR_ARGUMENTS}}
			);
		}

		#region Get*FromSlotDataDictionary

		private static bool GetBoolFromSlotDataDictionary(
			global::System.Collections.Generic.Dictionary<string, object?> slotData,
			string key,
			bool fallbackValue,
			global::BepInEx.Logging.ManualLogSource logger
		)
		{
			if (!(slotData.TryGetValue(key, out object? valueUntyped)))
			{
				string logMsg = $""The slot data does not contain an entry with the key \""{key}\"". "" +
					$""Falling back to the value {fallbackValue}."";
				logger.LogWarning(logMsg);

				return fallbackValue;
			}

			if (valueUntyped is null)
			{
				string logMsg = $""The slot data entry with the key \""{key}\"" is null. "" +
					$""Falling back to the value {fallbackValue}."";
				logger.LogWarning(logMsg);

				return fallbackValue;
			}

			if (!(valueUntyped is bool valueBool))
			{
				string logMsg = $""The slot data entry with the key \""{key}\"" is not a boolean. "" +
					$""Its actual type is {valueUntyped.GetType()}. "";

				switch (valueUntyped.ToString().ToLower())
				{
					case ""true"":
					case ""yes"":
					case ""on"":
					{
						logMsg += $""Using its coerced string representation instead. (true)"";
						logger.LogWarning(logMsg);

						return true;
					}
					case ""false"":
					case ""no"":
					case ""off"":
					{
						logMsg += $""Using its coerced string representation instead. (false)"";
						logger.LogWarning(logMsg);

						return false;
					}
					default:
					{
						logMsg += ""Coercing its string representation failed as well. "" +
							$""Falling back to the value {fallbackValue}"";
						logger.LogWarning(logMsg);

						return fallbackValue;
					}
				}
			}

			return valueBool;
		}

		private static int GetInt32FromSlotDataDictionary(
			global::System.Collections.Generic.Dictionary<string, object?> slotData,
			string key,
			int minValue,
			int maxValue,
			int fallbackValue,
			global::BepInEx.Logging.ManualLogSource logger
		)
		{
			if (!(slotData.TryGetValue(key, out object? valueUntyped)))
			{
				string logMsg = $""The slot data does not contain an entry with the key \""{key}\"". "" +
					$""Falling back to the value {fallbackValue}."";
				logger.LogWarning(logMsg);

				return fallbackValue;
			}

			if (valueUntyped is null)
			{
				string logMsg = $""The slot data entry with the key \""{key}\"" is null. "" +
					$""Falling back to the value {fallbackValue}."";
				logger.LogWarning(logMsg);

				return fallbackValue;
			}

			if (!(valueUntyped is long valueInt64))
			{
				string logMsg = $""The slot data entry with the key \""{key}\"" is not an integer. "" +
					$""Its actual type is {valueUntyped.GetType()}. "";

				if (!(int.TryParse(valueUntyped.ToString(), out int valueParsed)))
				{
					logMsg += ""Parsing its string representation failed as well. "" +
						$""Falling back to the value {fallbackValue}"";
					logger.LogWarning(logMsg);

					return fallbackValue;
				}

				logMsg += $""Using its parsed string representation instead. ({valueParsed})"";
				logger.LogWarning(logMsg);

				return valueParsed;
			}

			if (valueInt64 < minValue)
			{
				string logMsg = $""The slot data entry with the key \""{key}\"" is less than {minValue}. "" +
					$""Falling back to the value {minValue}."";
				logger.LogWarning(logMsg);

				return minValue;
			}

			if (valueInt64 > maxValue)
			{
				string logMsg = $""The slot data entry with the key \""{key}\"" is greater than {maxValue}. "" +
					$""Falling back to the value {maxValue}."";
				logger.LogWarning(logMsg);

				return maxValue;
			}

			return (int)valueInt64;
		}

		private static string GetStringFromSlotDataDictionary(
			global::System.Collections.Generic.Dictionary<string, object?> slotData,
			string key,
			string fallbackValue,
			global::BepInEx.Logging.ManualLogSource logger
		)
		{
			if (!(slotData.TryGetValue(key, out object? valueUntyped)))
			{
				string logMsg = $""The slot data does not contain an entry with the key \""{key}\"". "" +
					$""Falling back to {DisplayString(fallbackValue)}."";
				logger.LogWarning(logMsg);

				return fallbackValue;
			}

			if (valueUntyped is null)
			{
				string logMsg = $""The slot data entry with the key \""{key}\"" is null. "" +
					$""Falling back to {DisplayString(fallbackValue)}."";
				logger.LogWarning(logMsg);

				return fallbackValue;
			}

			if (!(valueUntyped is string value))
			{
				string logMsg = $""The slot data entry with the key \""{key}\"" is not a string. "" +
					$""Its actual type is {valueUntyped.GetType()}. "" +
					""Using its string representation instead."";
				logger.LogWarning(logMsg);

				return valueUntyped.ToString();
			}

			return value;
		}

		private static string DisplayString(string str)
		{
			if (str == """")
			{
				return ""an empty string"";
			}

			string escaped = str.Replace(@""\"", @""\\"").Replace(""\"""", ""\\\"""");
			return $""to the string \""{escaped}\"""";
		}

		#endregion
	}
}
";

		public void Initialize(IncrementalGeneratorInitializationContext context)
		{
			IncrementalValueProvider<TextLineCollection> slotDataSchemaTextProvider = context.AdditionalTextsProvider
				.Where((AdditionalText file) => Regex.IsMatch(file.Path, @"(^|[/\\])shared[/\\]slot_data_schema.cfg$"))
				.Collect()
				.Select((ImmutableArray<AdditionalText> matchedFiles, CancellationToken cancellationToken) =>
				{
					AdditionalText singleFile = matchedFiles.SingleOrDefault()
						?? throw new Exception("Multiple slot data schema files are provided");

					SourceText contents = singleFile.GetText(cancellationToken)
						?? throw new Exception($"Could not read file {singleFile.Path}");

					return contents.Lines;
				});

			context.RegisterSourceOutput(slotDataSchemaTextProvider, GenerateClassCodeFile);
		}

		private static void GenerateClassCodeFile(
			SourceProductionContext context,
			TextLineCollection slotDataSchemaTextLines
		)
		{
			Dictionary<string, SlotDataSchemaEntry> schema = SlotDataSchema.Parse(slotDataSchemaTextLines)
				?? throw new Exception("Invalid schema");

			string fileContents = FileContentsTemplate.SplitLines()
				.Select((Line line) =>
				{
					string lineText = line.Text;

					string indent = lineText.ExtractLeadingWhiteSpace();

					lineText = lineText
						.TrimStart()
						.Replace("{{NAMESPACE_NAME}}", NamespaceName)
						.Replace("{{FIELDS}}", () => GenerateClassFieldsCode(schema))
						.Replace("{{CONSTRUCTOR_PARAMETERS}}", () => GenerateClassConstructorParametersCode(schema))
						.Replace(
							"{{CONSTRUCTOR_FIELD_ASSIGNMENTS}}",
							() => GenerateClassConstructorFieldAssignmentsCodeCode(schema)
						)
						.Replace("{{TO_STRING_FIELDS}}", () => GenerateClassToStringFieldsCode(schema))
						.Replace(
							"{{FACTORY_FUNCTION_VARIABLES}}",
							() => GenerateClassFactoryFunctionVariablesCode(schema)
						)
						.Replace(
							"{{FACTORY_FUNCTION_CONSTRUCTOR_ARGUMENTS}}",
							() => GenerateClassFactoryFunctionConstructorArgumentsCode(schema)
						)
						.IndentWith(indent);

					return lineText + line.EolType.DetermineEolString();
				})
				.JoinToString("");

			context.AddSource($"{NamespaceName}.SlotData.g.cs", fileContents);
		}

		private static string GenerateClassFieldsCode(Dictionary<string, SlotDataSchemaEntry> schema)
		{
			return schema
				.Select((string key, SlotDataSchemaEntry entry) =>
				{
					var code = "";

					if (!(entry.Description is null))
					{
						// language=c#
						code += $@"/// <summary>
{entry.Description.PrependLinesWith("/// ")}
/// </summary>
";
					}

					// language=c#
					code += $"public readonly {entry.TypeData.DotNetTypeName} {PascalCase(key)};";

					return code;
				})
				.JoinToString(separator: "\n\n");
		}

		private static string GenerateClassConstructorParametersCode(Dictionary<string, SlotDataSchemaEntry> schema)
		{
			return schema
				// language=c#
				.Select((string key, SlotDataSchemaEntry entry) => $"{entry.TypeData.DotNetTypeName} {CamelCase(key)}")
				// language=c#
				.JoinToString(",\n");
		}

		private static string GenerateClassConstructorFieldAssignmentsCodeCode(
			Dictionary<string, SlotDataSchemaEntry> schema
		)
		{
			return schema.Keys
				// language=c#
				.Select((string key) => $"this.{PascalCase(key)} = {CamelCase(key)};")
				// language=c#
				.JoinToString("\n");
		}

		private static string GenerateClassToStringFieldsCode(Dictionary<string, SlotDataSchemaEntry> schema)
		{
			return schema
				.Select((string key, SlotDataSchemaEntry entry) =>
				{
					string fieldName = PascalCase(key);

					// language=c#
					return $"str += $\"{{nameof(this.{fieldName})}}: {{this.{fieldName}}}\";";
				})
				// language=c#
				.JoinToString("\nstr += \", \";\n");
		}

		private static string GenerateClassFactoryFunctionVariablesCode(Dictionary<string, SlotDataSchemaEntry> schema)
		{
			return schema
				.Select((string key, SlotDataSchemaEntry entry) =>
				{
					var code = "";

					// language=c#
					code += $"{entry.TypeData.DotNetTypeName} {CamelCase(key)} = ";

					switch (entry.TypeData)
					{
						case SlotDataSchemaEntryTypes.Bool boolData:
						{
							// language=c#
							code += $@"
	GetBoolFromSlotDataDictionary(
		slotData,
		key: ""{key}"",
		fallbackValue: {boolData.FallbackValue.ToString().ToLower()},
		logger
	);";
							break;
						}
						case SlotDataSchemaEntryTypes.Int32 int32Data:
						{
							// language=c#
							code += $@"
	GetInt32FromSlotDataDictionary(
		slotData,
		key: ""{key}"",
		minValue: {int32Data.MinValue},
		maxValue: {int32Data.MaxValue},
		fallbackValue: {int32Data.FallbackValue},
		logger
	);";
							break;
						}
						case SlotDataSchemaEntryTypes.String stringData:
						{
							// language=c#
							code += $@"
	GetStringFromSlotDataDictionary(
		slotData,
		key: ""{key}"",
		fallbackValue: ""{stringData.FallbackValue}"",
		logger
	);";
							break;
						}
						default: throw new Exception($"Unhandled entry type: {entry.TypeData.GetType()}");
					}

					return code;
				})
				// language=c#
				.JoinToString("\n\n");
		}

		private static string GenerateClassFactoryFunctionConstructorArgumentsCode(
			Dictionary<string, SlotDataSchemaEntry> schema
		)
		{
			return schema.Keys
				.Select(CamelCase)
				// language=c#
				.JoinToString(",\n");
		}

		private static string CamelCase(string snakeCaseString) =>
			StringUtils.TurnSnakeCaseIntoCamelCase(snakeCaseString);

		private static string PascalCase(string snakeCaseString) =>
			StringUtils.TurnSnakeCaseIntoPascalCase(snakeCaseString);
	}
}
